### ISSUE TITLE
Where is the JS file path?

### ISSUE THREAD

**Issue by starock** [maziac/binary-file-viewer#1]
Hi~ Thank you for the amzing plugin!

I'm trying to parse .wav file. Where is the path of wav.js?
I copyed file from yours. I don't know which path/folder should it put.

Help please , thank you!

**Comment by maziac** [comment]
It's in the settings:
![Bildschirmfoto 2022-06-25 um 22 24 49](https://user-images.githubusercontent.com/3081973/175789516-5a8f9ecc-ddc5-4360-ad59-a40d16e668e2.jpg)

You can add not only one, but a few different folders if you like.

**Comment by starock** [comment]
> 

Cool~! Thank you!
