### ISSUE TITLE
Feature Request: support ${workspaceFolder} ?

### ISSUE THREAD

**Issue by xackery** [maziac/binary-file-viewer#10]
Love the idea.

A tid bit not covered on the README/help
in your .vscode/settings.json, you can add:
```json
"workbench.editorAssociations": {
    "*.mod": "binary-file-viewer.viewer",
    "*.mds": "binary-file-viewer.viewer"
}

```
to automatically open *.mod and *.mds files with your extension if in the workspace.

I'd like to ask for support for variable parsing like ${workspaceFolder}, so I can define the js files in a workspace and build it into my repo.. with that, this is I think perfect for me to start building out some ideas I have
e.g. in my .vscode/settings.json:
```json
"binary-file-viewer.parserFolders": [
        "${workspaceFolder}/.vscode/parsers/"
    ]
```

Would let me put the parsers into the .vscode folder, out of mind of my primary work, and other folks who clone it can take advantage.

Thanks for making this!

**Comment by maziac** [comment]
- "to automatically open *.mod and *.mds files with your extension if in the workspace."
Thanks for the hint. I can add that.

- "${workspaceFolder}/.vscode/parsers/"
Something like that could be possible. I will have a look.
Probably one could also simply use a relative path, e.g. ".vscode/parsers/" could be recognized as a relative path and the workspace folder could be added.

**Comment by xackery** [comment]
<img width="353" alt="Screen Shot 2023-04-11 at 2 50 50 PM" src="https://user-images.githubusercontent.com/845670/231295939-03e62355-78dc-4e22-bd5f-af45de984c42.png">
Regarding second one, sadly nope..

**Comment by xackery** [comment]
<img width="166" alt="Screen Shot 2023-04-11 at 2 51 36 PM" src="https://user-images.githubusercontent.com/845670/231296095-3436f7cb-7a1e-4d3c-b9cc-7ed46cab67e2.png">
for ref

**Comment by maziac** [comment]
No, I meant: it could be implemented like that.

**Comment by maziac** [comment]
I have now experimented with this approach. But there is a problem.
If you have 'binary-file-viewer.parserFolders' set in a workspace folder it will override the user setting.
E.g. if you have certain parse files in a global folder you would need to add it here at this level as well.

**Comment by xackery** [comment]
A consideration for that concern:
https://marketplace.visualstudio.com/items?itemName=sumneko.lua

"Lua.workspace.library": []
<img width="768" alt="Screen Shot 2023-04-14 at 12 10 45 PM" src="https://user-images.githubusercontent.com/845670/232135306-a43fa164-b9df-4afc-adaa-1c0aeab925ab.png">

**Comment by xackery** [comment]
Really, if you could just add a detection for a special folder pattern inside the workspace e.g. .vscode/binary-ext/ and parse any js files in there, you can retain the settings how they work now, e.g. "binary-file-viewer.parserFolders": keep as a user setting that enables "global load" paths, but for folks who want a workspace-scoped project, you can do a light directory check for the binary-ext subdir of current workspace, and if you add .js files into it, they'll be parsed.

That way you don't have to add new settings, and it enables both ways of usage?

**Comment by maziac** [comment]
Maybe I found a way to deal with it.
The version below looks for relative paths in the workspace folder settings but **additionally** looks into the path for the workspace (multi root) or user settings.
The workspace folder setting can be a relative path (relative to the workspace folder), the others need to be absolute paths.
please give it a try:
[binary-file-viewer-1.7.3-rc1.vsix.zip](https://github.com/maziac/binary-file-viewer/files/11236972/binary-file-viewer-1.7.3-rc1.vsix.zip)

(But it seems it can get rather confusing...)

**Comment by xackery** [comment]
if I understand this correctly, I can just use:
```json
"binary-file-viewer.parserFolders": [
        ".vscode/parsers/"
    ],
```

right?

it does indeed seem to work, but I do get a message that:
<img width="438" alt="Screen Shot 2023-04-14 at 5 40 13 PM" src="https://user-images.githubusercontent.com/845670/232174598-5eda4fec-3c70-44c9-bed5-2cbe5890ad7b.png">

**Comment by xackery** [comment]
After that initial message.. it went away and seems to be loading clean. Unsure if there's a reload failure mechanism or something.

**Comment by maziac** [comment]
Please try this:
[binary-file-viewer-1.7.3-rc2.vsix.zip](https://github.com/maziac/binary-file-viewer/files/11239526/binary-file-viewer-1.7.3-rc2.vsix.zip)

**Comment by xackery** [comment]
No more nag I think, looking solid
