### ISSUE TITLE
Feature Request: View in Hex Editor

### ISSUE THREAD

**Issue by xackery** [maziac/binary-file-viewer#11]
So, there's this cool Reload button on the upper half.
Something I find myself often doing is right clicking the tab and going to `Reopen Editor With...` to switch to the Msft Hex Editor extension that lets me see the raw binary data.

Any thoughts of making this a button, too? Not sure best approach, just thought it may be an idea worth considering.

**Comment by maziac** [comment]
I personally don't think that it's worth the effort and I even don't know if it is easily possible from one extension to open another one.

And there is only a little convenience added: you could as well right from the beginning right-click the file twice and open it once with the binary-file-viewer and once with "Open with ..." with any other hex viewer.
