### ISSUE TITLE
Viewing of Packed Files

### ISSUE THREAD

**Issue by AndyJBuchanan** [maziac/binary-file-viewer#16]
Sometimes the files I'm trying to view will be compressed (lha in this case, but I have other files I want to get to that will have used zip) but I'd like the binary viewer to run on the contents.

I don't see any way through the API to handle this situation. 

Do you have any suggestions? I'm guessing I most likely need to bite the bullet and write a custom viewer Extension for this.

**Comment by maziac** [comment]
I'm afraid that 'unzip' functionality is not available in the binary-file-viewer.
