### ISSUE TITLE
Open different file in parser to fetch additional information

### ISSUE THREAD

**Issue by ghost** [maziac/binary-file-viewer#18]
Hi and thanks for very useful tool.

Is there a possibility to open different file in parser and use it to retrieve additional date?
In my case we have proprietary binary storage with separate 'catalog' and 'data' files. I need to fetch size of data chunk from 'catalog' file when parsing 'data' file.

I know exact position of bytes in catalog file with the data chunk size so I just need to be able to open catalog file and fetch bytes at exact offset.

**Comment by maziac** [comment]
This would probably be a bigger "journey".
The files are displayed in a web view and the parser is also running in that context.
The file itself is serialized and send to the web view from the vscode extension.
Reading a file directly in the web view certainly has access right problems.
Furthermore the read-file function is not available.

Probably this is not impossible to do, but out of scope for me.
But feel free to fork.
