### ISSUE TITLE
Options for basic user interaction

### ISSUE THREAD

**Issue by KONEY** [maziac/binary-file-viewer#19]
Hello!

I'm building a parser for Amiga .raw images, starting from the [.pic parser](https://github.com/maziac/binary-file-viewer/blob/main/examples/parsers/pic.js), which is working so far:

![image](https://github.com/user-attachments/assets/6a567763-1b28-46af-87c6-e049198e606a)

But .raw format has no information at all about dimensions/depth, this is also the reason why there aren't any viewers around. My workaround was to hardcode them in the parser itself but it would be nice to either decode these values from the filename or prompt some kind of interaction with the user, like maybe some fillable input fields. Is any of these options possible somehow?

Thanks

**Comment by maziac** [comment]
A UI for this is probably difficult to incorporate.
Parsing the filename on the other hand should be doable.
I could e.g. pass the filename to the function registered by registerParser. 
Then you could retrieve the information yourself from the filename.

**Comment by KONEY** [comment]
Would be ace! It's quite a standard to add x_y values to .raw filenames because there will be no other way to know the information, so yes it would be perfect!

**Comment by maziac** [comment]
Please find a vsix with that feature below.
I haven't updated any documentation yet but this version will pass the file path to your parser function.
I.e.:
~~~
registerParser: (func: (filePath: string) => void) => {
  ... do something with the absolute filePath 
~~~

Let me know if it works for you.

[binary-file-viewer-1.10.0-rc1.vsix.zip](https://github.com/user-attachments/files/16740425/binary-file-viewer-1.10.0-rc1.vsix.zip)

**Comment by KONEY** [comment]
it works perfectly, thanks!
