### ISSUE TITLE
Hardcoded inline width in canvas element

### ISSUE THREAD

**Issue by KONEY** [maziac/binary-file-viewer#20]
Hello, great work with this binary viewer!

I noticed the [canvas element](https://github.com/maziac/binary-file-viewer/blob/main/src/html/canvas.ts) has a hardcoded inline width property set at 100%, which forces it to adapt its size. This is not the ideal option for low resolution images as they get stretched. Maybe turn it into a max-width could be a better one but my best suggestion would be to provide a setter method enabling injection of inline CSS from the parser itself.

Hope this helps improving!

Regards

**Comment by maziac** [comment]
If you create a canvas e.g. `const ctx = addCanvas(1000, 300, 'My Canvas')` can't you simply change its properties like:
~~~
ctx.canvas.width = ...
~~~

**Comment by KONEY** [comment]
I didn't try but inspecting the markup I can tell the canvas already has the correct width applied:

`<canvas width="320" height="360" style="width: 100%;"></canvas>`

but there's an inline styling which forces the canvas to adapt to the window by stretching. This is hardcoded:

`	canvas.style.width = '100%';
`

**Comment by maziac** [comment]
Yes, there is the hardcoded width line.
I meant: after you used 'addCanvas' can't you simple change it to e.g. ctx.canvas.style.width = '50%', overriding the hardcoded value.

**Comment by KONEY** [comment]
oh yes it does work!! :)
