### ISSUE TITLE
different colors?

### ISSUE THREAD

**Issue by JohnKozell** [maziac/binary-file-viewer#22]
Is there a way to [easily] customize the colors used for the headings and data?
For example, the Size column magenta color is very difficult to read.
![image](https://github.com/user-attachments/assets/1a4ca3cc-4d64-44fe-838c-b9374cee9a79)

**Comment by maziac** [comment]
Yes, maybe I should make this customizable.

For now what you could do is to add 
~~~

	const elements = this.document.querySelectorAll('.size');
	elements.forEach(element => {
		element.style.color = 'red';
	});
~~~
 at the **end** of your registerParser function.

Before you ask :-) the other columns are called
- offset
- size
- name
- value
- description

**Comment by JohnKozell** [comment]
Perfect, thank you.
Yes, making it customizable would be nice but as long as there is a workaround time better spent on higher priority functional enhancements.

However, I think the 'detail' expansion is lazily executed and the code in registerParser doesn't seem to affect that, any suggestions for getting the detail color changed?

[edit] never mind, I figured that out. I had to place an additional occurance of the style manipulation inside the 'addDetails()' funcdtion.
Thanks again!

**Comment by l3dotdev** [comment]
Just as an additional note to this, I used a method to set the css vars directly because my vscode theme has conflicting colours for the 2 chosen.

```js
const root = this.document.querySelector(":root");
root.style.setProperty("--vscode-editorIndentGuide-background", "#1b1b1b");
root.style.setProperty("--vscode-badge-background", "#222");
```
