### ISSUE TITLE
`Date` built-in not available in parser file

### ISSUE THREAD

**Issue by l3dotdev** [maziac/binary-file-viewer#24]
Hey, I recently had to create my own function to convert a timestamp into a human-readable format because it seems like the javascript `Date` built-in doesn't exist in the parser file context.

I would love if this could be added for code simplicity!

**Comment by maziac** [comment]
I will check if it's possible.

**Comment by l3dotdev** [comment]
Wow, thanks for the *extremely* fast response! I've just noticed that things like `ArrayBuffer` and `DataView` are also not defined, these would also be great to have!

**Comment by maziac** [comment]
Please check version 1.11.0 (should be in the marketplace soon).

**Comment by l3dotdev** [comment]
Works great, thanks!
