### ISSUE TITLE
API addDetails Property

### ISSUE THREAD

**Issue by jinxie0731** [maziac/binary-file-viewer#25]
HI,

From the help.md, I get to know "addDetails is used to make rows expandable. I.e. when using addDetails the previous row gets a '+' sign, and If you click it with the mouse the row expands". But when I tried this feature using API readBits and addRow, what I got is a '-' sign.

My question is, is there a property to control the detailed rows to be not expanded automatically by default, as my parser has  a lot of bit field, and automatically expand all content seems making the preview a bit messy.

**Comment by maziac** [comment]
Hi,
addDetails has a 2nd parameter if set to fasle the display will start collapsed, e.g. like this:
~~~js
	addDetails(() => {
		readBits(1);
		addRow('Flag 0', getNumberValue(), 'Bit 0');
		readBits(3);
		addRow('Count', getDecimalValue(), 'Bits 1-3');
		readBits(4);
		addRow('Reserved');
	}, false);  <---------------
~~~

**Comment by maziac** [comment]
A problem here is that vscode's signature provider does provide the needed help like here:
![Bildschirmfoto 2024-10-29 um 17 21 18](https://github.com/user-attachments/assets/c9fe4b9f-860e-4167-8b8f-4afe1207f764)
but only if the whole function is on the same line.

**Comment by jinxie0731** [comment]
> Hi, addDetails has a 2nd parameter if set to fasle the display will start collapsed, e.g. like this:
> 
> ```js
> 	addDetails(() => {
> 		readBits(1);
> 		addRow('Flag 0', getNumberValue(), 'Bit 0');
> 		readBits(3);
> 		addRow('Count', getDecimalValue(), 'Bits 1-3');
> 		readBits(4);
> 		addRow('Reserved');
> 	}, false);  <---------------
> ```

cool, using parameter 'false' looks better, thank you very much.

**Comment by jinxie0731** [comment]
> A problem here is that vscode's signature provider does provide the needed help like here: ![Bildschirmfoto 2024-10-29 um 17 21 18](https://private-user-images.githubusercontent.com/3081973/381217159-c9fe4b9f-860e-4167-8b8f-4afe1207f764.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTY3MTcsIm5iZiI6MTczMDI5NjQxNywicGF0aCI6Ii8zMDgxOTczLzM4MTIxNzE1OS1jOWZlNGI5Zi04NjBlLTQxNjctOGI4Zi00YWZlMTIwN2Y3NjQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMTM1MzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDczZTU3MTE0NmVkMjIzN2ViNTEzMjc1NTFiOGUyNzg5ZDI2MjQ3NDczZDk1ODBmODAwY2IwMTBlMzhjYzg5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FTecicvderzVEUkXOW4iRt51C72jaZ3kGVhM5_Vr_2s) but only if the whole function is on the same line.

So that's how it is  : - ).
Although I'm just starting out, this extension is really useful for me as it can easily decode binary into a human readable format.

**Comment by maziac** [comment]
Note for myself. I looked into the signature problem, but parsing for a multiline command with all possibilities seems to be too much effort. So I will stick to the one-line implementation.
