### ISSUE TITLE
Question: Changing values

### ISSUE THREAD

**Issue by jakubsuchybio** [maziac/binary-file-viewer#4]
Hi,
is it possible to change values that are parsed with this specification?
I can see it super usefull.
If this is not possible, would you consider adding this functionality?
Thank you :)

**Comment by maziac** [comment]
At the moment I see this only as a viewer. Implementing editing functionality will add a lot of complexity.
So, to answer your question: no it cannot change values and I'm not planning to implement this feature.
But feel free to fork :-)
