### ISSUE TITLE
Reading data from any file position

### ISSUE THREAD

**Issue by KlausAschenbrenner** [maziac/binary-file-viewer#5]
Hello,

I've found the Binary File Viewer and I find it quite useful :-)
Is there any way to read some data from a binary file just from a specific file position?
As far as I have seen you can only read an input file forward with the given amount of bytes - through the "read()" function.

This is enough for easy file formats, but what about more complex ones - like the ELF or PE binary format? To be able to proper parse such files, you have to read data from specific offsets which you know after you have parsed the file header. You would need in the Parser function access to a function like "getBytesAt" to be able to freely "move around" in the binary file.

Thanks,

-Klaus

**Comment by maziac** [comment]
Yes, that' right. The idea is to continuously move the read pointer.

Can't you just read the header first and parse all the information you need ?

**Comment by KlausAschenbrenner** [comment]
That would be possible, but you also need the possibility to move backwards - and also forwards - in the binary file.

Thanks, Klaus

Sent from my iPhone

On 12.11.2022, at 18:09, maziac ***@***.***> wrote:

﻿

Yes, that' right. The idea is to continuously move the read pointer.

Can't you just read the header first and parse all the information you need ?

**Comment by KlausAschenbrenner** [comment]
Would be there any problem by providing a "getBytesAt" function available within the parser functionality?

**Comment by maziac** [comment]
A 'getBytesAt' does not fit into the concept.
There is a 'read' function with parameter size.

What I am thinking of is maybe a function that sets the offset to a different value and one function to read the current offset.
I.e. one could read/store the current offset, set to some other offset and restore the offset afterwards.

**Comment by KlausAschenbrenner** [comment]
A function that sets the offset to a different value would work perfectly! :-)

Sent from my iPhone

On 14.11.2022, at 18:36, maziac ***@***.***> wrote:

﻿

A 'getBytesAt' does not fit into the concept.
There is a 'read' function with parameter size.

What I am thinking of is maybe a function that sets the offset to a different value and one function to read the current offset.
I.e. one could read/store the current offset, set to some other offset and restore the offset afterwards.

**Comment by maziac** [comment]
Here is a version you can try out with
setOffset() and getOffset():
[binary-file-viewer-1.6.0-rc1.vsix.zip](https://github.com/maziac/binary-file-viewer/files/10047686/binary-file-viewer-1.6.0-rc1.vsix.zip)

A brief description can be found in the help text.

Please let me know if it works for you.

**Comment by maziac** [comment]
Is it still required?

**Comment by KlausAschenbrenner** [comment]
Currently not, thanks for your help.

From: maziac ***@***.***>
Reply to: maziac/binary-file-viewer ***@***.***>
Date: Tuesday, 29 November 2022 at 22:21
To: maziac/binary-file-viewer ***@***.***>
Cc: Klaus Aschenbrenner ***@***.***>, Author ***@***.***>
Subject: Re: [maziac/binary-file-viewer] Reading data from any file position (Issue #5)


Is it still required?

**Comment by maziac** [comment]
Could you at least verify that it is working.

**Comment by maziac** [comment]
No response.
