### ISSUE TITLE
Can't use a variable with the read() function

### ISSUE THREAD

**Issue by turgu1** [maziac/binary-file-viewer#7]
Hello, thanks a lot for this addOn!

Is it possible to use a variable to contain the number of bytes to read using the read() function?

My tests just don't work with a variable. The for loop doesn't seems to work too. Here is an  example of .js file:

``` javascript
registerFileType((fileExt, filePath, fileData) => {
	// Check for wav extension
	if (fileExt == 'ibmf') {
		const headerArray = fileData.getBytesAt(0, 4);
		const header = String.fromCharCode(...headerArray)
		if (header == 'IBMF')
			return true;
	}
	return false;
});

registerParser(() => {
	var faceCount;

	read(6);
	addRow('PREAMBLE', '', 'IBMF Preamble');
	addDetails(() => {
		read(4);
		addRow('Marker', getStringValue());
		read(1);
		faceCount = getNumberValue();
		addRow('Face Count', faceCount);
		readBits(5);
		addRow('File Version', getNumberValue(), '0 = LATIN, 1 = UTF32');
		readBits(3);
		addRow("Font Format", getNumberValue());
	});

	var byteCount = 4 * faceCount;
	read(byteCount);
	addRow('FACES OFFSETS', '', 'Faces Offsets');
	addDetails(() => {
		for (let i = 0; i < faceCount; i++) {
			read(4);
			addRow('Face', getNumberValue(), 'Offset from the beginning of the file');
		}
	});
});
```
Here is the result:

![image](https://user-images.githubusercontent.com/174329/226075937-c957a469-0eb4-43e7-b6e1-871a6eded881.png)

Thanks!
Guy Turcotte

**Comment by maziac** [comment]
I will have a look.
Could you maybe add a ibmf file for testing.

**Comment by turgu1** [comment]
Here is an ibmf file (you will have to unzip it...): 
[EC-Regular_100.ibmf.zip](https://github.com/maziac/binary-file-viewer/files/11008242/EC-Regular_100.ibmf.zip)

**Comment by turgu1** [comment]
I found something: If I add a comment string parameter to all addRows  functions I get a better result, but there is still a size not being shown:

Here is the .js:
``` javascript
registerFileType((fileExt, filePath, fileData) => {
	// Check for wav extension
	if (fileExt == 'ibmf') {
		const headerArray = fileData.getBytesAt(0, 4);
		const header = String.fromCharCode(...headerArray)
		if (header == 'IBMF')
			return true;
	}
	return false;
});

registerParser(() => {
	var faceCount = 0;

	read(6);
	addRow('PREAMBLE', '', 'IBMF Preamble');
	addDetails(() => {
		read(4);
		addRow('Marker', getStringValue(), 'Must be the string "IBMF"');
		read(1);
		faceCount = getNumberValue();
		addRow('Face Count', faceCount, 'How many face there is in the file');
		readBits(5);
		addRow('File Version', getNumberValue(), 'Font structure version number');
		readBits(3);
		addRow("Font Format", getNumberValue(), '0 = LATIN, 1 = UTF32');
	});

	var byteCount = 4 * faceCount;
	read(byteCount);
	addRow('FACES OFFSETS', '', 'Faces Offsets');
	addDetails(() => {
		for (let i = 0; i < faceCount; i++) {
			read(4);
			addRow('Face', getNumberValue(), 'Offset from the beginning of the file');
		}
	});
});
```

And the result:

![image](https://user-images.githubusercontent.com/174329/226100372-199017cf-e33d-469f-82b0-8e917006dbb6.png)

**Comment by maziac** [comment]
Please help me, I'm a little confused: The title says "Can't use a variable with the read() function" but in the description you don't use a variable for read() or I overlooked it.
Then "The for loop doesn't seems to work too". But obviously in your last picture it can be expanded (in the first picture I can't tell, he picture is not big enough).
And last there is no size for the FACES OFFSETS.

Please clarify especially the first 2.

read() should also work with a variable. 
Why size is not shown I have to look into.

**Comment by turgu1** [comment]
Sorry for the confusion... there is a variable used in the last details portion:

```javascript

	var byteCount = 4 * faceCount;
	read(byteCount);  // <--- Here is the variable
	addRow('FACES OFFSETS', ' ', 'Faces Offsets');
	addDetails(() => {
		for (let i = 0; i < faceCount; i++) {
			read(4);
			addRow('Face', getNumberValue(), 'Offset from the beginning of the file');
		}
	});
```

I was expecting that the comment parameter was optional. Then it started to work by adding the comments parameter. Is it supposed to work without the parameter?

**Comment by turgu1** [comment]
The first picture was complete: nothing was shown below the last row, even if it was supposed to show the details.

**Comment by maziac** [comment]
Please forget my previous comment.
I see now what is happening.
The addDetails function is collapsed by default. I.e. it is not executed. This is because of performance reasons.
If it would contain a lot of parsing and you would have many of these commands in your parser then the initial opening can take some time. Therefore the parsing is simply delayed until the section is expanded.
In your case byteCount was  not set correctly because faceCount was undefined.

There is an easy solution to your problem: open the details right away by adding the parameter 'true':
![Bildschirmfoto 2023-03-18 um 12 18 47](https://user-images.githubusercontent.com/3081973/226102068-a3d41ca1-bc1f-4501-9f33-c681521df50c.jpg)

Of course a more correct way would be to extract the data in any case (no matter if collapsed or expanded), you can do that e.g. with readRowWithDetails.

See here for a complete solution:

~~~js
registerFileType((fileExt, filePath, fileData) => {
	// Check for wav extension
	if (fileExt == 'ibmf') {
		const headerArray = fileData.getBytesAt(0, 4);
		const header = String.fromCharCode(...headerArray)
		if (header == 'IBMF')
			return true;
	}
	return false;
});

registerParser(() => {
	var faceCount;

	readRowWithDetails('PREAMBLE', () => {
		read(4);
		addRow('Marker', getStringValue());
		read(1);
		faceCount = getNumberValue();
		addRow('Face Count', faceCount);
		readBits(5);
		addRow('File Version', getNumberValue(), '0 = LATIN, 1 = UTF32');
		readBits(3);
		addRow("Font Format", getNumberValue());
		return {description: 'IBMF Preamble'};
	});

	var byteCount = 4 * faceCount;
	read(byteCount);
	addRow('FACES OFFSETS', '', 'Faces Offsets');
	addDetails(() => {
		for (let i = 0; i < faceCount; i++) {
			read(4);
			addRow('Face', getNumberValue(), 'Offset from the beginning of the file');
		}
	});
});
~~~

which results in:
![Bildschirmfoto 2023-03-18 um 12 46 03](https://user-images.githubusercontent.com/3081973/226103621-fba86907-c706-4865-b16f-150e4aaf95e5.jpg)

or expanded:
![Bildschirmfoto 2023-03-18 um 12 46 22](https://user-images.githubusercontent.com/3081973/226103635-9a4ee6e3-a415-42b6-98e0-222977b8de85.jpg)

**Comment by turgu1** [comment]
Excellent!!! It works like a charm!
Thanks a lot!

**Comment by maziac** [comment]
I will add another error message to the binary file viewer, so that it is easier to spot.
