### ISSUE TITLE
How to change parser?

### ISSUE THREAD

**Issue by ThaDaVos** [maziac/binary-file-viewer#8]
It seems it uses the first parser it can find - or at least, it's not using my custom parser. Any way to change this?
![afbeelding](https://user-images.githubusercontent.com/5251028/230411495-285900d7-9f79-4b83-a969-420d66a4c812.png)

**Comment by ThaDaVos** [comment]
Okay, it seems to be loading my parser - but not using my format for some reason?
```JavaScript
registerFileType((fileExt, filePath, fileData) => {
    if (['lib', 'g.lib'].includes(fileExt)) {
        return true;
    }
    
    return false;
});

registerParser(() => {
    read(1);
    addRow('Type', getHexOxValue(), 'Record Type');

    read(2);
    const recordLength = getNumberValue();
    addRow('Length', recordLength, 'The full length of the record');

    read(recordLength);
    addRow('Data', getStringValue(), 'Data');
});
```

**Comment by ThaDaVos** [comment]
Trying to create a parser for this:
http://www.azillionmonkeys.com/qed/Omfg.pdf

**Comment by maziac** [comment]
In the problems area you should find the hint:
![Bildschirmfoto 2023-04-06 um 19 28 56](https://user-images.githubusercontent.com/3081973/230452736-59c25754-887d-4bbc-a54e-a0acce5892b0.jpg)
Actually you used a 'O' instead of a '0' (zero) inside getHex0xValue.

If you change it and save, you should see your parsed file:
![Bildschirmfoto 2023-04-06 um 19 30 28](https://user-images.githubusercontent.com/3081973/230453042-a8062cb8-a8ce-4257-bfcc-7da632a8b563.jpg)

**Comment by ThaDaVos** [comment]
Two things:

1. How did you get highlighting?
2. All methods were through auto-completion/intellisense - so how that typo got in, I wouldn't know - or it's the one I copied from the "Getting Started" example of the WAV file

**Comment by maziac** [comment]
1. Which highlighting? the red squiggles?
They come from the binary file viewer extension. Any errors are also written to the PROBLEMS pane.
Is it not working for you?
You need to save the js file before it is analyzed.

3. For me it displays the correct suggestion:
![Bildschirmfoto 2023-04-06 um 21 31 21](https://user-images.githubusercontent.com/3081973/230476848-1401ae78-32e0-463f-8678-4d15bdebcefc.jpg)
You can see the text 'Binary File Viewer' to the right of the suggestions which shows the origin.
The others are probably from intellisense
Maybe you chose the wrong auto-completion.

**Comment by ThaDaVos** [comment]
1. Is not working for me - do I need to select a specific format? Or do I need to edit the parser file from a window where the extension itself is also being used? Auto completion works though
2. It does for me too - but it doesn't show the errors

I also found the source for my error, see: https://github.com/maziac/binary-file-viewer/blob/204b98100ecf7be0689ac41795d62df43c1dd6b3/assets/local/help/help.md?plain=1#L100

**Comment by maziac** [comment]
1. Yes, while developing a parser file you need to have the parser file and the parsed file in the same vscode window.
The cause of this is explained a little bit here: [filewatcher](https://github.com/maziac/binary-file-viewer/blob/main/design/overall.md#filewatcher)

2. Thanks for the hint. I will correct that.

**Comment by ThaDaVos** [comment]
1. Thanks, good to know
2. You're welcome!

Another question - as you can see in http://www.azillionmonkeys.com/qed/Omfg.pdf the binary file contains multiple records - I was under the impression I could show each record as a separate line through the parser - but it only works with rows - not columns - is this possible at all?

**Comment by maziac** [comment]
" I was under the impression I could show each record as a separate line through the parser - but it only works with rows - not columns "

Could you elaborate a bit. I don't understand the problem.

**Comment by ThaDaVos** [comment]
No elaboration needed - I was mistaken how Binary files work 🤣
